### ISSUE TITLE
USB DP Display on Rock5B

### ISSUE THREAD

**Issue by UtsavBalar1231** [openFyde/overlay-rock5b-openfyde#15]
I have recently tested this OS on my rock 5b and really require the need for DP display.  I have modified my rock 5b to provide 5V external power supply so that, I can use the freed typec port as DP. I have a DP to VGA adapter that I have using with my rock pi 4b for CDN DP which works well and good. I have tinkered with kernel a bit as well to enable DP aux support on usbdp_phy0 but it does not work.

![modifed-rock5b](https://user-images.githubusercontent.com/32286881/230714301-c3889b91-ce44-4aaa-8187-448f34196cd1.jpg)

I am available for testing any of your builds, thanks

**Comment by Damenly** [comment]
Thanks for your testing and report.
May I ask if DP outputs normally on official Debian/Armbian? If it works, could you elaborate on how did you make it? so I can confirm what we can do for your ask.
If it does not, I think it's better to ask in radxa form since openfyde uses radxa's kernel directly.

**Comment by UtsavBalar1231** [comment]
Sadly it doesn't work on radxa's kernel. I read the rk3588 usb dp guide and followed the instructions as mentioned there. But, it never worked with rock 5b.
